# docker-compose.yml
version: '3.8'

services:
  # OTEL Collector - Receives metrics, traces, logs from FastAPI
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    container_name: otel-collector
    command: ["--config=/etc/otelcol-contrib/config.yml"]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otelcol-contrib/config.yml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver  
      - "8889:8889"   # Prometheus metrics endpoint
      - "13133:13133" # Health check
    depends_on:
      - prometheus
      - tempo
      - loki
    networks:
      - monitoring

  # Prometheus - Scrapes metrics from OTEL Collector
  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=24h'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring

  # Grafana - Visualizes metrics from Prometheus
  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
      - tempo
      - loki
    networks:
      - monitoring

  # Tempo - Distributed tracing backend
  tempo:
    image: grafana/tempo:2.3.0
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/tmp/tempo
    ports:
      - "3200:3200"   # Tempo HTTP API
      - "4327:4317"   # OTLP gRPC receiver (external port 4327)
      - "4328:4318"   # OTLP HTTP receiver (external port 4328)
      - "9095:9095"   # Tempo gRPC
    networks:
      - monitoring

  # Loki - Log aggregation
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
    networks:
      - monitoring

volumes:
  prometheus_data:
  grafana_data:
  tempo_data:
  loki_data:

networks:
  monitoring:
    driver: bridge