# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # Add alerting rules here later

scrape_configs:
  # Scrape FastAPI metrics from OTEL Collector
  - job_name: 'fastapi-via-otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 10s
    metrics_path: /metrics
    honor_labels: true

  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Optional: Scrape OTEL Collector's own metrics
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888']
    metrics_path: /metrics
    scrape_interval: 30s